import type {
  QuestionnaireDefinition,
  QuestionDefinition,
  QuestionInputType,
  SurveySectionDefinition,
} from "@/lib/survey/types";

const YES_NO = ["Yes", "No"];
const YES_NO_DK = ["Yes", "No", "Don't Know"];
const AREA_UNITS = ["Nali", "Acre", "Hectare"];
const PRODUCTION_UNITS = ["kg", "Quintal", "Tonne"];
const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const INCOME_SOURCES = ["Horticulture", "Other Crops", "Livestock", "Farm Labour", "Non-Farm Labour", "Salary", "Business", "Forest Products", "Remittances", "Pension", "Government Transfers", "Other"];
const FPO_SERVICES = ["Inputs", "Planting Material", "Training", "Extension", "Credit", "Machinery", "Aggregation", "Marketing", "Storage", "Processing", "Transport"];

const q = (
  id: string,
  label: string,
  inputType: QuestionInputType,
  options?: string[],
  extra: Partial<QuestionDefinition> = {},
): QuestionDefinition => ({ id, label, inputType, options, treatmentControlApplicability: "both", ...extra });

const section = (
  id: string,
  order: number,
  title: string,
  shortTitle: string,
  description: string,
  questions: QuestionDefinition[],
  instrument: "household" | "institutional" = "household",
): SurveySectionDefinition => ({ id, order, title, shortTitle, description, questions, instrument });

const unit = (id: string, label: string, units: string[], extra: Partial<QuestionDefinition> = {}) =>
  q(id, label, "unit_number", undefined, { unitOptions: units, ...extra });

const money = (id: string, label: string, extra: Partial<QuestionDefinition> = {}) =>
  q(id, label, "currency", undefined, { unit: "INR", validation: { min: 0 }, ...extra });

const householdSections: SurveySectionDefinition[] = [
  section(
    "demographic-profile",
    1,
    "Demographic Profile of Sample Households",
    "Demographics",
    "Consent, survey identification, household roster, land, housing, assets, and basic services.",
    [
      q("1.1", "Does the respondent provide informed consent to participate?", "radio", ["Yes - Consent Provided", "No - Consent Not Provided"], { required: true, helpText: "If consent is not provided, the interview must end." }),
      q("1.2", "Survey ID", "automatic", undefined, { calculation: "survey_id", required: true }),
      q("1.3", "Survey round", "select", ["Baseline", "Midline", "Endline"], { required: true }),
      q("1.4", "Study group", "radio", ["Treatment", "Control"], { required: true }),
      q("1.5", "District", "search_select", ["Nainital", "Pithoragarh", "Tehri Garhwal", "Uttarkashi"], { required: true }),
      q("1.6", "Block", "search_select", undefined, { required: true, helpText: "Options will be filtered from the approved District-Block master." }),
      q("1.7", "FPO / analytical cluster", "search_select", undefined, { required: true, helpText: "Configure the 16 approved project FPOs in master data." }),
      q("1.8", "Village", "search_select", ["Other - Specify"], { required: true, helpText: "Options will be filtered by District, Block, and FPO." }),
      q("1.9", "Respondent name", "text", undefined, { required: true }),
      q("1.10", "Respondent contact number", "phone", undefined, { placeholder: "10-digit mobile or leave blank if unavailable", validation: { pattern: "^[6-9][0-9]{9}$" } }),
      q("1.11", "GPS location", "gps", undefined, { required: true, helpText: "Capture latitude, longitude, accuracy, and timestamp." }),
      q("1.12", "Religion", "select", ["Hindu", "Muslim", "Sikh", "Christian", "Buddhist", "Jain", "Other", "Prefer Not to Answer"]),
      q("1.13", "Social category", "select", ["SC", "ST", "OBC", "General", "Other", "Prefer Not to Answer"], { required: true }),
      q("1.14", "EWS status", "radio", YES_NO_DK),
      q("1.15", "Disability / vulnerability status", "multiselect", ["Person with Disability", "Elderly-Headed", "Female-Headed", "Single-Parent", "Chronically Vulnerable Household", "Other", "None", "Prefer Not to Answer"]),
      q("1.16", "Family type", "radio", ["Nuclear", "Joint", "Extended", "Other"], { required: true }),
      q("1.17", "Housing type", "select", ["Kutcha", "Semi-Pucca", "Pucca", "Other"]),
      q("1.18", "Electricity access", "radio", ["Yes - Reliable", "Yes - Intermittent", "No"]),
      q("1.19", "Distance to motorable road", "number", undefined, { unit: "km", validation: { min: 0 } }),
      q("1.20", "Travel time to motorable road", "number", undefined, { unit: "minutes", validation: { min: 0 } }),
      q("1.21", "Main drinking water source", "select", ["Piped Supply", "Spring", "Stream", "Handpump", "Borewell", "Well", "Tanker", "Other"]),
      q("1.22", "Drinking water reliability", "radio", ["Available Year-Round", "Seasonal Shortage", "Frequent Shortage", "Severe Shortage"]),
      q("1.23", "Household toilet", "radio", ["Functional", "Non-Functional", "No Toilet"]),
      q("1.24", "Household assets", "multiselect", ["Smartphone", "Basic Phone", "TV", "Refrigerator", "Computer", "Two-Wheeler", "Car", "Internet", "Other"]),
      q("1.25", "Land tenure", "multiselect", ["Owned with Title", "Customary/Ancestral", "Leased-In", "Leased-Out", "Sharecropped", "Community/Common Land", "Other"]),
      unit("1.26", "Land owned", AREA_UNITS),
      unit("1.27", "Land leased-in", AREA_UNITS),
      unit("1.28", "Land leased-out", AREA_UNITS),
      unit("1.29", "Cultivated land", AREA_UNITS),
      unit("1.30", "Irrigated land", AREA_UNITS),
      unit("1.31", "Horticultural land", AREA_UNITS),
      q("1A", "Household member roster", "repeat_group", undefined, {
        required: true,
        repeatLabel: "household member",
        minRepeats: 1,
        fields: [
          q("1A.1", "Member name", "text", undefined, { required: true }),
          q("1A.2", "Age", "number", undefined, { required: true, unit: "years", validation: { min: 0, max: 120 } }),
          q("1A.3", "Gender", "radio", ["Male", "Female", "Other", "Prefer Not to Answer"], { required: true }),
          q("1A.4", "Relationship to household head", "select", ["Head", "Spouse", "Son", "Daughter", "Parent", "Sibling", "Son-in-Law", "Daughter-in-Law", "Grandchild", "Other"], { required: true }),
          q("1A.5", "Education", "select", ["Below School Age", "No Formal Schooling", "Primary", "Middle", "Secondary", "Higher Secondary", "Diploma-ITI", "Graduate", "Postgraduate+"]),
          q("1A.6", "Primary occupation", "select", ["Horticulture", "Agriculture", "Livestock", "Farm Labour", "Non-Farm Labour", "Government Job", "Private Job", "Business", "Homemaker", "Student", "Unemployed", "Retired", "Other"]),
          q("1A.7", "Secondary occupation", "select", ["None", "Horticulture", "Agriculture", "Livestock", "Farm Labour", "Non-Farm Labour", "Government Job", "Private Job", "Business", "Homemaker", "Student", "Unemployed", "Retired", "Other"]),
          q("1A.8", "Engaged in agriculture", "radio", YES_NO),
          q("1A.9", "Engaged in horticulture", "radio", YES_NO),
          q("1A.10", "Engaged in processing", "radio", YES_NO),
          q("1A.11", "Migration status", "select", ["No Migration", "Seasonal", "Temporary", "Long-Term", "Permanent"]),
          q("1A.12", "Mobile number", "phone", undefined, { placeholder: "Optional - no personal phone is permitted" }),
          q("1A.13", "FPO member", "radio", YES_NO),
          q("1A.14", "SHG member", "radio", YES_NO),
        ],
      }),
    ],
  ),
  section(
    "financial-profile",
    2,
    "Household Income Sources and Financial Profile",
    "Income & finance",
    "Income, expenditure, savings, debt, credit, insurance, schemes, and crop-loss-related financial stress.",
    [
      q("2.1", "Household income sources", "multiselect", INCOME_SOURCES, { required: true, recallPeriod: "Last 12 months" }),
      q("2.2", "Annual income by source", "repeat_group", undefined, { repeatLabel: "income source", showWhen: { questionId: "2.1", operator: "not_empty" }, recallPeriod: "Last 12 months", fields: [q("2.2a", "Income source", "select", INCOME_SOURCES, { required: true }), money("2.2b", "Approximate annual income", { required: true })] }),
      q("2.3", "Total annual income", "automatic", undefined, { calculation: "sum", dependsOn: ["2.2"], unit: "INR/year" }),
      money("2.4", "Annual food expenditure", { recallPeriod: "Last 12 months" }),
      money("2.5", "Annual agriculture / horticulture expenditure", { recallPeriod: "Last 12 months" }),
      money("2.6", "Annual education expenditure", { recallPeriod: "Last 12 months" }),
      money("2.7", "Annual health expenditure", { recallPeriod: "Last 12 months" }),
      money("2.8", "Annual transport expenditure", { recallPeriod: "Last 12 months" }),
      money("2.9", "Other major annual expenditure", { recallPeriod: "Last 12 months" }),
      q("2.10", "Total annual expenditure", "automatic", undefined, { calculation: "sum", dependsOn: ["2.4", "2.5", "2.6", "2.7", "2.8", "2.9"], unit: "INR/year" }),
      q("2.11", "Does the household have savings?", "radio", YES_NO),
      money("2.12", "Approximate savings", { showWhen: { questionId: "2.11", value: "Yes" } }),
      q("2.13", "Savings location", "multiselect", ["Bank", "Post Office", "SHG", "Cash", "Other"], { showWhen: { questionId: "2.11", value: "Yes" } }),
      q("2.14", "Does the household have outstanding debt?", "radio", YES_NO),
      money("2.15", "Outstanding debt amount", { showWhen: { questionId: "2.14", value: "Yes" } }),
      q("2.16", "Credit source", "multiselect", ["Bank", "RRB", "Cooperative", "SHG", "FPO", "MFI", "Moneylender", "Friends/Relatives", "Other"], { showWhen: { questionId: "2.14", value: "Yes" } }),
      q("2.17", "Loan purpose", "multiselect", ["Crop", "Orchard", "Irrigation", "Machinery", "Livestock", "Processing", "Health", "Education", "Consumption", "Other"], { showWhen: { questionId: "2.14", value: "Yes" } }),
      q("2.18", "Loan repayment status", "select", ["Fully Repaid", "Regular Repayment", "Delayed", "Defaulted", "Not Yet Due"], { showWhen: { questionId: "2.14", value: "Yes" } }),
      q("2.19", "Difficulty accessing credit", "radio", ["Very Difficult", "Difficult", "Moderate", "Easy", "Very Easy"]),
      q("2.20", "Awareness of crop insurance", "radio", YES_NO),
      q("2.21", "Is any crop currently insured?", "radio", YES_NO, { showWhen: { questionId: "2.20", value: "Yes" } }),
      q("2.22", "Insurance claim status", "select", ["No Claim", "Fully Paid", "Partially Paid", "Rejected", "Pending"], { showWhen: { questionId: "2.21", value: "Yes" } }),
      q("2.23", "Government scheme access", "repeat_group", undefined, { repeatLabel: "scheme", fields: [q("2.23a", "Scheme name", "text"), q("2.23b", "Year", "year"), q("2.23c", "Benefit type", "text"), q("2.23d", "Benefit received", "radio", YES_NO)] }),
      q("2.24", "Crop-loss-related financial stress", "radio", ["None", "Low", "Moderate", "High", "Severe"]),
      q("2.25", "Financial consequences of a major crop loss", "multiselect", ["Used Savings", "Borrowed Money", "Sold Assets", "Reduced Food Consumption", "Reduced Other Expenditure", "Took Additional Work", "Migration", "Other", "None"], { showWhen: { questionId: "2.24", operator: "not_equals", value: "None" } }),
    ],
  ),
  section(
    "crop-production",
    3,
    "Crop Production Practices - All Crops and Focus Crops",
    "Crop production",
    "All-crop records, focus crop status, productivity, input costs, improved technologies, and adoption potential.",
    [
      q("3.1", "Crop production roster", "repeat_group", undefined, {
        required: true,
        repeatLabel: "crop",
        minRepeats: 1,
        recallPeriod: "Most recently completed production season/cycle",
        fields: [
          q("3.1a", "Crop cultivated", "search_select", ["Other"], { required: true, helpText: "Crop master list will be configured from the approved project crop list." }),
          q("3.2", "Crop category", "select", ["Fruit", "Vegetable", "Spice", "Cereal", "Pulse", "Oilseed", "Other"], { required: true }),
          unit("3.3", "Area planted", AREA_UNITS, { required: true }),
          unit("3.4", "Area harvested", AREA_UNITS),
          unit("3.5", "Total production - current season", PRODUCTION_UNITS, { required: true }),
          unit("3.6", "Previous season production", PRODUCTION_UNITS),
          unit("3.7", "Quantity consumed at home", PRODUCTION_UNITS),
          unit("3.8", "Quantity retained for seed / farm use", PRODUCTION_UNITS),
          unit("3.9", "Quantity sold", PRODUCTION_UNITS),
          unit("3.10", "Quantity lost / damaged", PRODUCTION_UNITS),
          q("3.11", "Project focus crop status", "automatic", undefined, { calculation: "focus_crop_status", helpText: "Detected from the approved project focus-crop master." }),
          q("3.12", "Variety", "search_select", ["Other"], { helpText: "Variety master can be configured by crop." }),
          q("3.13", "Variety type", "radio", ["Local", "Improved", "Hybrid", "Don't Know"]),
          q("3.14", "Orchard age", "number", undefined, { unit: "years", showWhen: { questionId: "3.2", value: "Fruit" }, validation: { min: 0 } }),
          q("3.15", "Planting material source", "select", ["Own", "FPO", "Government Nursery", "Private Nursery", "Dealer", "Other"]),
          q("3.16", "Irrigation method", "multiselect", ["Rainfed", "Flood", "Furrow", "Drip", "Sprinkler", "Other"]),
          q("3.17", "Mulching adopted", "radio", YES_NO),
          q("3.18", "IPM adopted", "radio", YES_NO_DK),
          q("3.19", "INM adopted", "radio", YES_NO_DK),
          q("3.20", "Yield / productivity", "automatic", undefined, { calculation: "yield", dependsOn: ["3.3", "3.5"], unit: "kg/acre and kg/ha" }),
          q("3.21", "Benchmark yield comparison", "automatic", undefined, { helpText: "Calculated only after a validated secondary benchmark database is configured." }),
          money("3.22", "Planting material cost"),
          money("3.23", "Fertilizer / manure cost"),
          money("3.24", "Plant protection cost"),
          money("3.25", "Irrigation cost"),
          q("3.26", "Family labour", "number", undefined, { unit: "person-days", validation: { min: 0 } }),
          q("3.27", "Hired labour", "number", undefined, { unit: "person-days", validation: { min: 0 } }),
          money("3.28", "Hired labour cost"),
          money("3.29", "Machinery cost"),
          money("3.30", "Harvest / post-harvest cost"),
          money("3.31", "Other production cost"),
          q("3.32", "Total cost of cultivation", "automatic", undefined, { calculation: "cost_total", dependsOn: ["3.22", "3.23", "3.24", "3.25", "3.28", "3.29", "3.30", "3.31"], unit: "INR" }),
          q("3.33", "Improved technology adopted", "multiselect", ["Polyhouse", "Shade Net", "Drip", "Sprinkler", "Improved Variety", "Other", "None"]),
          q("3.34", "Rank the top three production constraints", "rank", ["Pest/Disease", "Water", "Labour", "Input Cost", "Input Availability", "Climate", "Wildlife", "Finance", "Technology", "Market", "Other"], { validation: { maxSelections: 3 } }),
        ],
      }),
      q("3A.STATUS", "Household focus-crop cultivation status", "automatic", undefined, { calculation: "focus_crop_status", dependsOn: ["3.1"], helpText: "Determined across the crop roster after focus-crop master data is configured." }),
      q("3A.1", "Previously cultivated the target focus crop", "radio", YES_NO, { showWhen: { questionId: "3A.STATUS", value: "Non-grower" } }),
      q("3A.2", "Willingness to adopt the focus crop", "radio", ["Definitely Yes", "Probably Yes", "Unsure", "Probably No", "Definitely No"], { showWhen: { questionId: "3A.STATUS", value: "Non-grower" } }),
      q("3A.3", "Suitable land available", "radio", YES_NO_DK, { showWhen: { questionId: "3A.STATUS", value: "Non-grower" } }),
      q("3A.4", "Irrigation available", "radio", YES_NO, { showWhen: { questionId: "3A.STATUS", value: "Non-grower" } }),
      q("3A.5", "Knowledge of focus-crop production", "radio", ["High", "Moderate", "Low", "None"], { showWhen: { questionId: "3A.STATUS", value: "Non-grower" } }),
      q("3A.6", "Access to planting material", "radio", ["Easy", "Moderate", "Difficult", "No Access"], { showWhen: { questionId: "3A.STATUS", value: "Non-grower" } }),
      q("3A.7", "Expected market opportunity", "radio", ["Very Good", "Good", "Moderate", "Poor", "Don't Know"], { showWhen: { questionId: "3A.STATUS", value: "Non-grower" } }),
      q("3A.8", "Main barriers to adopting the focus crop", "multiselect", ["Land", "Water", "Planting Material", "Knowledge", "Labour", "Finance", "Climate Risk", "Market Risk", "Other"], { showWhen: { questionId: "3A.STATUS", value: "Non-grower" } }),
    ],
  ),
  section(
    "inputs-extension",
    4,
    "Access to Inputs and Extension Services",
    "Inputs & extension",
    "Availability, quality, affordability, timeliness, suppliers, extension contact, training, and digital advisory services.",
    [
      q("4.1", "Planting material availability", "radio", ["Always", "Usually", "Sometimes", "Rarely", "Never"]),
      q("4.2", "Planting material quality", "radio", ["Very Good", "Good", "Average", "Poor", "Very Poor"]),
      q("4.3", "Planting material affordability", "radio", ["Very Affordable", "Affordable", "Moderate", "Expensive", "Very Expensive"]),
      q("4.4", "Planting material timeliness", "radio", ["Always on Time", "Usually", "Sometimes", "Rarely", "Never"]),
      q("4.5a", "Fertilizer availability", "radio", ["Always", "Usually", "Sometimes", "Rarely", "Never"]),
      q("4.5b", "Fertilizer quality", "radio", ["Very Good", "Good", "Average", "Poor", "Very Poor"]),
      q("4.5c", "Fertilizer affordability", "radio", ["Very Affordable", "Affordable", "Moderate", "Expensive", "Very Expensive"]),
      q("4.5d", "Fertilizer timeliness", "radio", ["Always on Time", "Usually", "Sometimes", "Rarely", "Never"]),
      q("4.6a", "Pesticide availability", "radio", ["Always", "Usually", "Sometimes", "Rarely", "Never"]),
      q("4.6b", "Pesticide quality", "radio", ["Very Good", "Good", "Average", "Poor", "Very Poor"]),
      q("4.6c", "Pesticide affordability", "radio", ["Very Affordable", "Affordable", "Moderate", "Expensive", "Very Expensive"]),
      q("4.6d", "Pesticide timeliness", "radio", ["Always on Time", "Usually", "Sometimes", "Rarely", "Never"]),
      q("4.7a", "Tools / equipment availability", "radio", ["Always", "Usually", "Sometimes", "Rarely", "Never"]),
      q("4.7b", "Tools / equipment quality", "radio", ["Very Good", "Good", "Average", "Poor", "Very Poor"]),
      q("4.7c", "Tools / equipment affordability", "radio", ["Very Affordable", "Affordable", "Moderate", "Expensive", "Very Expensive"]),
      q("4.7d", "Tools / equipment timeliness", "radio", ["Always on Time", "Usually", "Sometimes", "Rarely", "Never"]),
      q("4.8", "Main input source", "select", ["FPO", "Government", "Cooperative", "Private Dealer", "Nursery", "Other"]),
      q("4.9", "Distance to input source", "number", undefined, { unit: "km", validation: { min: 0 } }),
      q("4.10", "Access to extension services", "radio", YES_NO),
      q("4.11", "Extension provider", "multiselect", ["Horticulture Department", "Agriculture Department", "KVK", "FPO", "NGO", "Private", "Other"], { showWhen: { questionId: "4.10", value: "Yes" } }),
      q("4.12", "Type of extension contact", "multiselect", ["Farm Visit", "Office Visit", "Group Meeting", "Demonstration", "Phone", "Digital", "Other"], { showWhen: { questionId: "4.10", value: "Yes" } }),
      q("4.13", "Extension contact frequency", "select", ["Weekly", "Monthly", "Quarterly", "1-2 Times/Year", "Never"], { showWhen: { questionId: "4.10", value: "Yes" } }),
      q("4.14", "Last extension contact", "select", ["Less than 1 Month", "1-3 Months", "4-6 Months", "7-12 Months", "More than 1 Year"], { showWhen: { questionId: "4.10", value: "Yes" } }),
      q("4.15", "Advisory topic", "multiselect", ["Crop Production", "Pest-Disease", "Nutrition", "Irrigation", "Climate", "Post-Harvest", "Marketing", "Other"], { showWhen: { questionId: "4.10", value: "Yes" } }),
      q("4.16", "Was the advice adopted?", "radio", YES_NO, { showWhen: { questionId: "4.10", value: "Yes" } }),
      q("4.17", "Training received", "radio", YES_NO),
      q("4.18", "Training provider", "multiselect", ["UKIHDP", "FPO", "KVK", "Department", "NGO", "Private", "Other"], { showWhen: { questionId: "4.17", value: "Yes" } }),
      q("4.19", "Training usefulness", "radio", ["Very Useful", "Useful", "Somewhat Useful", "Not Useful"], { showWhen: { questionId: "4.17", value: "Yes" } }),
      q("4.20", "Digital advisory platform used", "multiselect", ["WhatsApp", "SMS", "App", "YouTube", "Website", "Social Media", "None"]),
    ],
  ),
  section(
    "processing",
    5,
    "Processing Practices and Infrastructure",
    "Processing",
    "Primary and secondary processing, facilities, processing economics, barriers, and PMFME awareness.",
    [
      q("5.1", "Primary processing practices", "multiselect", ["Sorting", "Grading", "Packing", "None"]),
      q("5.2", "Does the household process produce?", "radio", YES_NO),
      q("5.3", "Processing type", "multiselect", ["Jam", "Pickle", "Juice", "Pulp", "Drying", "Other"], { showWhen: { questionId: "5.2", value: "Yes" } }),
      unit("5.4", "Quantity processed", PRODUCTION_UNITS, { showWhen: { questionId: "5.2", value: "Yes" } }),
      money("5.5", "Processing cost", { showWhen: { questionId: "5.2", value: "Yes" } }),
      money("5.6", "Processed product revenue", { showWhen: { questionId: "5.2", value: "Yes" } }),
      q("5.7", "Processing location", "select", ["Household", "FPO", "SHG", "Community Facility", "Private Unit", "Other"], { showWhen: { questionId: "5.2", value: "Yes" } }),
      q("5.8", "Facility ownership", "select", ["Own", "FPO", "SHG", "Government", "Private", "Community"], { showWhen: { questionId: "5.2", value: "Yes" } }),
      q("5.9", "Facility capacity utilization", "radio", ["Less than 25%", "25-50%", "51-75%", "More than 75%", "Don't Know"], { showWhen: { questionId: "5.2", value: "Yes" } }),
      q("5.10", "Access to a packhouse", "radio", YES_NO),
      q("5.11", "Access to a processing unit", "radio", YES_NO),
      q("5.12", "Reasons for not processing", "multiselect", ["No Equipment", "High Cost", "Lack Skills", "Low Volume", "No Market", "No Finance", "Other"], { showWhen: { questionId: "5.2", value: "No" } }),
      q("5.13", "Awareness of PMFME", "radio", YES_NO),
    ],
  ),
  section(
    "marketing",
    6,
    "Aggregation, Distribution and Marketing",
    "Marketing",
    "Markets, buyers, sale conditions, marketing costs, grading, post-harvest losses, aggregation, information, and contracts.",
    [
      q("6.1", "Main buyer", "select", ["FPO", "Trader", "Mandi", "Wholesaler", "Retailer", "Processor", "Direct Consumer", "Contract Buyer", "Other"]),
      q("6.2", "Market name", "text"),
      q("6.3", "Distance to market", "number", undefined, { unit: "km", validation: { min: 0 } }),
      q("6.4", "Transport mode", "select", ["On Foot", "Animal", "Two-Wheeler", "Own Vehicle", "Hired Vehicle", "FPO Transport", "Public Transport", "Other"]),
      q("6.5", "Selling period", "multiselect", MONTHS),
      unit("6.6", "Quantity sold", PRODUCTION_UNITS),
      unit("6.7", "Selling price", ["INR/kg", "INR/quintal"]),
      q("6.8", "Payment timing", "select", ["Immediate", "Within 7 Days", "8-30 Days", "More than 30 Days"]),
      q("6.9", "Availability of alternative buyers", "select", ["Many", "Few", "One", "None"]),
      money("6.10", "Transport cost"),
      money("6.11", "Loading / unloading cost"),
      money("6.12", "Commission"),
      money("6.13", "Market fee"),
      money("6.14", "Packaging cost"),
      money("6.15", "Storage cost"),
      q("6.16", "Was produce graded?", "radio", YES_NO),
      q("6.17", "Was produce rejected or downgraded?", "radio", YES_NO),
      q("6.18", "Reason for rejection / downgrading", "multiselect", ["Size", "Appearance", "Damage", "Disease", "Ripeness", "Quality", "Other"], { showWhen: { questionId: "6.17", value: "Yes" } }),
      unit("6.19", "Post-harvest loss quantity", PRODUCTION_UNITS),
      q("6.20", "Post-harvest loss percentage", "number", undefined, { unit: "%", validation: { min: 0, max: 100 }, helpText: "May be entered or calculated where a comparable total quantity is available." }),
      q("6.21", "Stage of loss", "multiselect", ["Harvest", "Sorting", "Packing", "Storage", "Transport", "Market"]),
      q("6.22", "Cause of loss", "multiselect", ["Damage", "Spoilage", "Poor Storage", "Transport", "Delay", "Rejection", "Other"]),
      q("6.23", "FPO aggregation used", "radio", YES_NO),
      q("6.24", "Collective marketing used", "radio", YES_NO),
      q("6.25", "Market information source", "multiselect", ["FPO", "Trader", "Mandi", "Government", "Mobile", "Internet", "Other"]),
      q("6.26", "Contract or pre-agreed buyer", "radio", YES_NO),
      q("6.27", "Contract type", "radio", ["Written", "Verbal"], { showWhen: { questionId: "6.26", value: "Yes" } }),
    ],
  ),
  section(
    "risks",
    7,
    "Risks and Challenges",
    "Risks",
    "Natural, crop, wildlife, and market shocks, their losses, and household coping mechanisms.",
    [
      q("7.1", "Shock / hazard experience", "repeat_group", undefined, {
        repeatLabel: "shock or hazard",
        recallPeriod: "Most recent event and typical frequency",
        fields: [
          q("7.1a", "Shock / hazard", "select", ["Frost", "Hail", "Drought", "Flood", "Landslide", "Heavy Rain", "Wildlife", "Pest", "Disease", "Market Shock"], { required: true }),
          q("7.2", "Frequency", "radio", ["Once", "Occasionally", "Frequently", "Every Season"]),
          q("7.3", "Severity", "radio", ["Low", "Moderate", "High", "Severe"]),
          q("7.4a", "Most recent year", "year"),
          q("7.4b", "Most recent season", "select", ["Kharif", "Rabi", "Zaid/Summer", "Perennial/Annual Cycle", "Other"]),
          q("7.5", "Estimated production loss", "number", undefined, { unit: "%", validation: { min: 0, max: 100 } }),
          money("7.6", "Estimated income loss"),
          q("7.7", "Coping mechanism", "multiselect", ["Savings", "Borrowing", "Insurance", "Diversification", "Off-Farm Work", "Migration", "Reduced Consumption", "Other"]),
          q("7.8", "Coping effectiveness", "radio", ["Very Effective", "Effective", "Partly Effective", "Ineffective"]),
        ],
      }),
    ],
  ),
  section(
    "nutrition",
    8,
    "Household Nutrition Security",
    "Nutrition",
    "Food production, kitchen gardens, dietary diversity, consumption frequency, shortage, coping, and scheme access.",
    [
      q("8.1", "Household food production", "multiselect", ["Cereals", "Pulses", "Vegetables", "Fruits", "Milk", "Eggs", "Meat", "Other"]),
      q("8.2", "Kitchen / nutri garden present", "radio", YES_NO),
      q("8.3", "Food groups consumed during the previous 24 hours", "multiselect", ["Cereals", "Roots and Tubers", "Vegetables", "Fruits", "Pulses", "Nuts and Seeds", "Dairy", "Eggs", "Meat", "Fish", "Oils and Fats", "Sweets"], { recallPeriod: "Previous 24 hours", helpText: "Confirm the final food-group standard against the approved dietary-diversity protocol before field deployment." }),
      q("8.4", "Fruit consumption frequency", "select", ["Daily", "4-6 Days/Week", "2-3 Days/Week", "Weekly", "Less Often", "Never"]),
      q("8.5", "Vegetable consumption frequency", "select", ["Daily", "4-6 Days/Week", "2-3 Days/Week", "Weekly", "Less Often", "Never"]),
      q("8.6", "Contribution of own horticultural production to household diet", "radio", ["Very High", "High", "Moderate", "Low", "None"]),
      q("8.7", "Did the household experience food shortage?", "radio", YES_NO, { recallPeriod: "Last 12 months" }),
      q("8.8", "Months of food shortage", "multiselect", MONTHS, { showWhen: { questionId: "8.7", value: "Yes" } }),
      q("8.9", "Food-shortage coping strategies", "multiselect", ["Reduce Portions", "Skip Meals", "Borrow Food", "Purchase on Credit", "Less Preferred Foods", "Other"], { showWhen: { questionId: "8.7", value: "Yes" } }),
      q("8.10", "Awareness of POSHAN", "radio", YES_NO),
      q("8.11", "Access to Anganwadi services", "radio", ["Yes", "No", "Not Applicable"]),
    ],
  ),
  section(
    "climate-adaptation",
    9,
    "Environmental Sustainability and Climate Adaptation",
    "Climate adaptation",
    "Adaptation and conservation practices, support, effectiveness, barriers, advisories, and future preparedness.",
    [
      q("9.1", "Adaptation practices", "repeat_group", undefined, {
        repeatLabel: "adaptation practice",
        fields: [
          q("9.1a", "Practice", "select", ["Mulching", "Water Harvesting", "Drip", "Sprinkler", "Soil Conservation", "Orchard Rejuvenation", "Resilient Variety", "Diversification", "Protected Cultivation", "Other"], { required: true }),
          q("9.2", "Year adopted", "year"),
          q("9.3", "Source of support", "select", ["Self", "FPO", "Government", "UKIHDP", "NGO", "Other"]),
          q("9.4", "Perceived effectiveness", "radio", ["Very Effective", "Effective", "Partly Effective", "Ineffective"]),
        ],
      }),
      q("9.5", "Barriers to adaptation", "multiselect", ["Cost", "Knowledge", "Labour", "Water", "Land", "Technology", "Finance", "Other"]),
      q("9.6", "Willingness to adopt additional measures", "radio", ["Very Willing", "Willing", "Unsure", "Unwilling"]),
      q("9.7", "Climate advisory received", "radio", YES_NO),
      q("9.8", "Climate advisory source", "multiselect", ["Government", "FPO", "KVK", "SMS", "WhatsApp", "App", "TV-Radio", "Other"], { showWhen: { questionId: "9.7", value: "Yes" } }),
      q("9.9", "Confidence in future climate preparedness", "radio", ["Very Confident", "Confident", "Neutral", "Not Confident", "Not at All Confident"]),
    ],
  ),
  section(
    "gender-youth-inclusion",
    10,
    "Gender, Youth and Social Inclusion",
    "Inclusion",
    "Division of work, decisions, income control, women's participation, youth engagement, social inclusion, and household-FPO linkage.",
    [
      q("10.1", "Who performs key farm activities?", "matrix", undefined, { rows: ["Land preparation", "Planting", "Irrigation", "Input application", "Harvesting", "Post-harvest / processing", "Marketing"], columns: ["Mainly Men", "Mainly Women", "Joint", "Hired Labour", "Other"] }),
      q("10.2", "Who makes key farm and household decisions?", "matrix", undefined, { rows: ["Crop selection", "Input purchase", "Irrigation", "Technology adoption", "Labour hiring", "Produce sales", "Buyer selection", "Use of farm income", "Credit", "FPO participation", "Training participation"], columns: ["Man Mainly", "Woman Mainly", "Jointly", "Other"] }),
      q("10.3", "Who controls farm income?", "radio", ["Man Mainly", "Woman Mainly", "Jointly", "Other"]),
      q("10.4", "Women's combined farm and household workload", "number", undefined, { unit: "approximate hours/day", validation: { min: 0, max: 24 } }),
      q("10.5", "Women's training participation", "radio", YES_NO),
      q("10.6", "Women's FPO / SHG participation", "multiselect", ["FPO", "SHG", "Both", "Neither"]),
      q("10.7", "Women's leadership role", "select", ["Board/Director", "Office Bearer", "SHG Leader", "Other Leadership", "Member Only", "None"]),
      q("10.8", "Project youth age definition", "automatic", undefined, { helpText: "Configure the project-approved youth age range before deployment." }),
      q("10.9", "Youth engaged in horticulture", "radio", YES_NO),
      q("10.10", "Youth interest in horticulture", "radio", ["High", "Moderate", "Low", "None"]),
      q("10.11", "Youth migration intention", "select", ["Stay", "Seasonal Migration", "Likely Migrate", "Already Migrated", "Unsure"]),
      q("10.12", "Youth interest in a horticultural enterprise", "radio", YES_NO),
      q("10.13", "Barriers to youth participation", "multiselect", ["Land", "Finance", "Skills", "Profitability", "Market", "Social Preference", "Other"]),
      q("10.14", "Social inclusion barriers", "multiselect", ["Finance", "Land", "Information", "Training", "Mobility", "Social Barriers", "Other", "None"]),
      q("10A.1", "Household FPO membership", "radio", YES_NO),
      q("10A.2", "FPO membership duration", "number", undefined, { unit: "years", showWhen: { questionId: "10A.1", value: "Yes" }, validation: { min: 0 } }),
      q("10A.3", "FPO participation frequency", "select", ["Monthly+", "Quarterly", "Occasionally", "Rarely", "Never"], { showWhen: { questionId: "10A.1", value: "Yes" } }),
      q("10A.4", "FPO services received during the last 12 months", "multiselect", FPO_SERVICES, { recallPeriod: "Last 12 months" }),
      q("10A.5", "Satisfaction with FPO services", "matrix", undefined, { rows: FPO_SERVICES, columns: ["Very Satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very Dissatisfied", "Not Received"] }),
      q("10A.6", "Produce sold through the FPO", "number", undefined, { unit: "%", showWhen: { questionId: "10A.1", value: "Yes" }, validation: { min: 0, max: 100 } }),
      q("10A.7", "Reason for non-membership", "multiselect", ["Not Aware", "Not Invited", "No Perceived Benefit", "Cost", "Distance", "Lack Trust", "Other"], { showWhen: { questionId: "10A.1", value: "No" } }),
      q("10A.8", "Reason for not using FPO services", "multiselect", ["Not Available", "Not Needed", "Poor Quality", "High Cost", "Distance", "Lack Information", "Other"]),
    ],
  ),
  section(
    "quality-control",
    11,
    "Enumerator Quality Control",
    "Quality control",
    "Interview timing, GPS quality, enumerator assessment, comments, and completeness validation.",
    [
      q("QC1", "Interview start", "automatic", undefined, { helpText: "Captured when the questionnaire is opened." }),
      q("QC2", "Interview end", "automatic", undefined, { helpText: "Captured when the questionnaire is submitted." }),
      q("QC3", "Interview duration", "automatic", undefined, { calculation: "interview_duration", unit: "minutes" }),
      q("QC4", "GPS accuracy", "automatic", undefined, { unit: "metres", dependsOn: ["1.11"] }),
      q("QC5", "Response reliability", "radio", ["High", "Moderate", "Low"], { required: true }),
      q("QC6", "Respondent understanding", "radio", ["Good", "Moderate", "Poor"], { required: true }),
      q("QC7", "Enumerator comments", "textarea", undefined, { placeholder: "Optional observations or data-quality concerns" }),
      q("QC8", "Completeness validation", "automatic", undefined, { calculation: "completeness" }),
    ],
  ),
];

const institutionalSections: SurveySectionDefinition[] = [
  section(
    "fpo-institutional",
    1,
    "Institutional Mapping and FPO Functioning",
    "FPO assessment",
    "A separate institutional tool covering FPO governance, membership, business readiness, performance, aggregation, services, infrastructure, convergence, and constraints.",
    [
      q("11.1", "FPO identification", "search_select", undefined, { required: true, helpText: "Configure the 16 approved project FPOs in master data." }),
      q("11.2", "Governance assessment", "matrix", undefined, { rows: ["Board functioning", "Meeting regularity", "Election process", "Member participation"], columns: ["Functional", "Partially Functional", "Non-Functional", "Not Available"] }),
      q("11.3", "Membership profile", "numeric_matrix", undefined, { rows: ["Total Members", "Women", "Youth", "SC", "ST", "OBC"], columns: ["Number"] }),
      q("11.4", "Business readiness", "radio", ["Very High", "High", "Moderate", "Low", "Very Low"]),
      q("11.5", "Financial / business performance", "numeric_matrix", undefined, { rows: ["Annual Turnover", "Annual Revenue", "Annual Profit or Loss"], columns: ["INR"] }),
      q("11.6", "Aggregation capacity", "number", undefined, { unit: "tonnes/year", validation: { min: 0 } }),
      q("11.7", "Infrastructure available", "multiselect", ["Collection Centre", "Nursery", "Packhouse", "Storage", "Cold Storage", "Processing"]),
      q("11.7a", "Infrastructure GPS location", "gps", undefined, { helpText: "Capture the assessed facility location where applicable." }),
      q("11.8", "Services provided", "multiselect", ["Inputs", "Training", "Credit", "Aggregation", "Marketing", "Storage", "Processing"]),
      q("11.9", "Scheme convergence", "multiselect", ["MIDH", "MGNREGS", "PMFME", "NABARD", "Other"]),
      q("11.10", "Rank the top three institutional constraints", "rank", ["Governance", "Finance", "Staff", "Infrastructure", "Membership", "Aggregation", "Market", "Other"], { validation: { maxSelections: 3 } }),
    ],
    "institutional",
  ),
];

export const projectMaster = {
  focusCrops: [] as string[],
  youthAgeRange: null as null | { min: number; max: number },
};

export const householdQuestionnaire: QuestionnaireDefinition = {
  id: "ukihdp-household-baseline",
  title: "UKIHDP Household Baseline Survey",
  version: "1.0-draft",
  status: "draft",
  sections: householdSections,
};

export const institutionalQuestionnaire: QuestionnaireDefinition = {
  id: "ukihdp-fpo-institutional",
  title: "UKIHDP FPO Institutional Assessment",
  version: "1.0-draft",
  status: "draft",
  sections: institutionalSections,
};
